### ISSUE TITLE
Question - Support for FHIR release 4

### ISSUE THREAD

**Issue by michelekorell** [Asymmetrik/graphql-fhir#16]
Hello, at the end of the last year HL7 released the 4.0.0 release that contain some normative elements, did you plan to support this release as extended endpoint?

http://www.hl7.org/fhir/directory.cfml

**Comment by Robert-W** [comment]
Hey @michelekorell, just responded to your post on chat.fhir.org. Yes we do and we plan to have it up very soon, we already have it working locally but just need to run some integration tests and it will be published !!!!

**Comment by michelekorell** [comment]
Thanks a lot and bests regards.

**Comment by Robert-W** [comment]
@michelekorell R4 is now supported, please see the release notes [here](https://github.com/Asymmetrik/graphql-fhir/releases/tag/v1.0.0) for more information.
