### ISSUE TITLE
Resources storage structure [Question]

### ISSUE THREAD

**Issue by eq0rip** [Asymmetrik/graphql-fhir#18]
Hello,
I am using graphql-fhir and using mongo as db. 
What structure do you suggest to use for different versions of resources ?
a. Store in same collection and map according to versions
b. Store in different collection as Patient_1_0_2, Patient_3_0_1 etc ?

**Comment by Robert-W** [comment]
Hi @eq0rip,

We are currently using option b in our sample applications, which is storing resources in different collections like `Patient_1_0_2` and `Patient_3_0_1`. This can give you many advantages with the only real disadvantage being management(of the databases themselves and with the connections inside your application) and making sure you are working with the correct collection.

We do expose the original express `req` which will contain the version information in it and you can use that to determine which collections to interact with.

**Comment by eq0rip** [comment]
Great @Robert-W. Will work on option b then. Thank you.

**Comment by Robert-W** [comment]
No problem, If you have any more questions feel free to open another issue.
