### ISSUE TITLE
Instance Query [Question]

### ISSUE THREAD

**Issue by eq0rip** [Asymmetrik/graphql-fhir#21]
Hello,

Following is the InstanceQuery I tried
```
http://localhost:3000/3_0_1/Questionnaire/jamana/$graphql?query={id}
```
I am receiving back response as `Cannot query field \"id\" on type \"Questionnaire_Query\" `

So what is the right format I should try ?

`https://build.fhir.org/graphql.html` has a sample as ` http://test.fhir.org/r3/Patient/example/$graphql?query={name{text,given,family}} `.Its working in their server.  I cannot get the response When I try similarly in our graph-fhir.

**Comment by Robert-W** [comment]
Hi @eq0rip, we are using named queries since we are using express-graphql. I do not believe that is valid syntax. Also, the url provided does not seem to work, I just get an OperationOutcome saying the patient does not exist, which is not a valid GraphQL response.

Can you try changing your query from:

```shell
http://localhost:3000/3_0_1/Questionnaire/jamana/$graphql?query={id}
```

to this:

```shell
http://localhost:3000/3_0_1/Questionnaire/jamana/$graphql?query={Questionnaire{id}}
```

When writing the query, you need to provide the return type as part of the instance query. You should get a response that looks like similar to this(if you have implemented your resolver you will have data and not null):

```json
{
  "data": {
    "Questionnaire": {
      "id": null
    }
  }
}
```

**Comment by eq0rip** [comment]
Tried 
```
GET /3_0_1/Questionnaire/jamana/$graphql?query={Questionnaire{id,title}} HTTP/1.1
Host: localhost:3000
Authorization: Bearer <access_token>
```
This time didnot receive error but still no data.

Below is the response
```
{
    "data": {
        "Questionnaire": {
            "id": null,
            "title": null
        }
    }
}
```

But I am receiving Proper data when I used `http://localhost:3000/3_0_1/$graphql?query={Questionnaire{id,title}}` which is not Instance Query.
```
{
    "data": {
        "Questionnaire": {
            "id": "jamana",
            "title": "ddddsf"
        }
    }
}
```


Can you please give me sample request for 
```
	instance: {
		name: 'Questionnaire',
		path: '/3_0_1/Questionnaire/:id',
		query: QuestionnaireInstanceQuery,
	},
```
this part of the code ?



As per `https://build.fhir.org/graphql.html`
> A System level query. The query must start by selecting a resource type and some search criteria, as defined below.

> [base]/[Type]/[id]/$graphql
> A Resource Instance level the query assumes a single resource is in scope, and just queries on the > data available in the given resource.

> GraphQL can be invoked by get with a query parameter, or a POST with the graphQL as the body, or a JSON body

**Comment by Robert-W** [comment]
If you are getting null then you are doing it correctly, but you haven't wrote a query or connected it to a data source. You still need to return the questionnaire in the resolver.

Where you are seeing this:

```javascript
instance: {
	name: 'Questionnaire',
	path: '/3_0_1/Questionnaire/:id',
	query: QuestionnaireInstanceQuery,
},
```

You are seeing the endpoint being registered with an `id` parameter, which is different from a GraphQL argument. This is just an express argument. If you navigate to the `questionnaire/query.js` file, you can see that the `QuestionnaireInstanceQuery` query has a different resolver than the standard `QuestionnaireQuery`. So in your `questionnaire/resolver.js` file, if you want both query and instance query to work, you need to implement both resolvers.

e.g.

```javascript
// This is for the standard query
module.exports.getQuestionnaire = function getQuestionnaire(
	root,
	args,
	context = {},
	info,
) {
	let { server, version, req, res } = context;
        // Do query and return questionnaire 
	return {};
};

// This one is for a questionnaire instance
module.exports.getQuestionnaireInstance = function getQuestionnaireInstance(
	root,
	args,
	context = {},
	info,
) {
	let { server, version, req, res } = context;
        // req.params.id is your questionnaire id, use that for your query here
	// queryQuestionnaireById does not exist, it is pseudo code
        // you need to query your database here with the id
        let questionnaire = queryQuestionnaireById(req.params.id);
        // return the correct questionnaire here, default returns {}, 
        // which is why you see null, because no data is returned
	return questionnaire;
};
```

**Comment by eq0rip** [comment]
Great. 
Sorry, my bad.
I had it commented out after my first error.

Got it working now. 

Thanks. @Robert-W

**Comment by Robert-W** [comment]
Awesome,

No problem, glad I could help!
