### ISSUE TITLE
Unable to insert answerOption in Questionnaire Resource

### ISSUE THREAD

**Issue by sureshHARDIYA** [Asymmetrik/graphql-fhir#27]
### Do you want to submit a request for change, improve documentation, or ask a question?
-  request for change, and ask a question

#### If reporting a bug, please answer the following at minimum and add any additional information you think may be helpful

**What is the current behavior?**
After defining resolvers and my Database connection, I tried to insert a questionnaire.
If you take for [example questionnaire as shown in here](http://hl7.org/fhir/questionnaire-example-bluebook.json.html):

It has `answerOption`:
```
"answerOption": [
                {
                  "valueCoding": {
                    "code": "F"
                  }
                },
                {
                  "valueCoding": {
                    "code": "M"
                  }
                }
              ]
```
But since schema requires [other values to be not here](https://github.com/Asymmetrik/graphql-fhir/blob/master/src/resources/4_0_0/schemas/questionnaireitemansweroption.schema.js#L47) we get error saying `valueInteger`, `valueString` and others are required. 

**What is the expected behavior?**
As shown in [the documentation] (http://hl7.org/fhir/questionnaire.html#resource)
![Screenshot 2019-05-09 at 16 34 43](https://user-images.githubusercontent.com/2022919/57462083-7bca2c80-7278-11e9-882a-2cf3106eb0a1.png)

If a question has only two options which are `valueCoding`, we should not have to define other values?

**What are the steps to reproduce?**
I tried a mutation to create a questionnaire  with `answerOption`. However, if I remove `GraphQLNonNull` from the lines: https://github.com/Asymmetrik/graphql-fhir/blob/master/src/resources/4_0_0/schemas/questionnaireitemansweroption.schema.js#L47, it works fine. So, my question would be, if we define `answerOption`, do we really need to define all those `[valueCoding, valueInteger, valueDecimal, valueDate, valueTime, valueReference]`. 

**What OS are you using and what version of node.js and @asymmetrik/graphql-fhir are you running?**
- node js: 10.0.0
- OS: MAC 

PS: If `GraphQLNonNull` is not required according to HL7 FHIR R4 definitions, I can create a PR if you like. 

Regards, 
Suresh

**Comment by Robert-W** [comment]
Hey @sureshHARDIYA, thanks for submitting this. 

This is indeed a bug. Looks like there is an issue in our code generation services we used to build the resources. Essentially, code gen sees value[x] as required and is incorrectly applying to each value[x] parameter, so as you noticed, it incorrectly expects valueCoding, valueDate, etc to all be required when it really should just be one of the group that is required. Ill submit a ticket to try to get this resolved in our generator and get a patch out soon. In the meantime, you can remove the GraphQLNonNull from those fields to allow the behavior you need.

**Comment by Robert-W** [comment]
Hey @sureshHARDIYA,

If you would like to submit a PR that would be great (We're going to update this in our generator but I am not sure we will have time to get to it until after dev days on June 10). We looked into this a little bit and it seems like we will have to remove the GraphQLNonNull. There is no way in GraphQL to really enforce the "one of these several different fields is required" logic. The only way to do this is to enforce it at the resolver level.

**Comment by sureshHARDIYA** [comment]
I can create PR.

**Comment by sureshHARDIYA** [comment]
@Robert-W Created a PR https://github.com/Asymmetrik/graphql-fhir/pull/28. Hope you review it and get it to merge and release a new version.

**Comment by Robert-W** [comment]
We have included notes about fixing this in the next batch of generated code, so this will not be re-introduced in the next release.
