### ISSUE TITLE
Is there a plan to support graphQL directives like @flatten and @first?

### ISSUE THREAD

**Issue by tian000** [Asymmetrik/graphql-fhir#34]
#### If reporting a bug, please answer the following at minimum and add any additional information you think may be helpful

**What is the current behavior?**

**What is the expected behavior?**

**What are the steps to reproduce?**

**What OS are you using and what version of node.js and @asymmetrik/graphql-fhir are you running?**

**Comment by Robert-W** [comment]
It's not on our immediate roadmap but is something we are aware of and may have added in the near future. We are of course always accepting pull requests if anyone has time to help in adding support for that feature in the meantime. Custom directives are nice and support in `graphql-js` does seem to exist, but there is not a lot of documentation on them.  We are not using Apollo or other tools, so if we want to add directives, we will need to implement them with `graphql-js`.

**Comment by malyalavenu** [comment]
Can you provide the internal tool mentioned in README to generate the FHIR profiles ? This is needed as many countries are having their own versions of the FHIR profiles. For example US has their own [core profile](https://www.hl7.org/fhir/us/core/) Datasets, India has their [own](https://nrces.in/ndhm/fhir/r4/index.html), that I know of. Access to the tool would help reuse the tool, and minimize errors
