### ISSUE TITLE
Request for running against revised FHIR specifications, particularly UKCore R4

### ISSUE THREAD

**Issue by jamesburtonqubithealth** [Asymmetrik/graphql-fhir#42]
### I would like to generate the resources for UKCore's R4 specification

Is there a method included with which we can generate against modified FHIR specifications, specifically for me the UKCore R4 implementation?
- https://simplifier.net/UKCore/~introduction

If it is possible for you guys to point at that and re-run the generators in a UKCoreR4 branch that would be amazing, but if you can point me in the right direction I'm also happy to act as a contributor here too.

**Comment by luan-dev** [comment]
Unfortunately, we do not support the UKCore at this time. If you would like to contribute and open a PR, I will gladly look at it
